<a href="https://colab.research.google.com/github/NandhithaMilkuri/Batch20_1352_PDS/blob/main/Lab2_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
Marks=np.array([[96,56,80],[67,89,78],[90,67,56],[89,90,78],[67,45,34]])
print(Marks)


[[96 56 80]
 [67 89 78]
 [90 67 56]
 [89 90 78]
 [67 45 34]]


In [16]:
avg_marks = Marks.mean(axis=1)
min_marks = Marks.min(axis=1)
max_marks = Marks.max(axis=1)
print("\nAverage marks per student:", avg_marks)
print("Minimum marks per student:", min_marks)
print("Maximum marks per student:", max_marks)


Average marks per student: [77.33333333 78.         71.         85.66666667 48.66666667]
Minimum marks per student: [56 67 56 78 34]
Maximum marks per student: [96 89 90 90 67]


In [18]:
print("\nMarks of Students 2 to 4:\n", Marks[1:4])


Marks of Students 2 to 4:
 [[67 89 78]
 [90 67 56]
 [89 90 78]]


In [25]:
above_80 = Marks[(Marks > 80).all(axis=1)]
print("\nStudents scoring above 80 in all subjects:\n", above_80)



Students scoring above 80 in all subjects:
 []


In [27]:
reshaped = Marks.T
print("\nSubject-wise performance:\n", reshaped)


Subject-wise performance:
 [[96 67 90 89 67]
 [56 89 67 90 45]
 [80 78 56 78 34]]


In [28]:
import pandas as pd

data = {
    'Name': ['Nandhu', 'Arun', 'Vamshi', 'Sneha', 'Srinidhi'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing'],
    'Salary': [48000, 55000, 72000, 50000, 65000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
        Name   ID Department  Salary
0    Nandhu  101         HR   48000
1      Arun  102         IT   55000
2    Vamshi  103    Finance   72000
3     Sneha  104         IT   50000
4  Srinidhi  105  Marketing   65000


In [29]:
high_salary = df[df['Salary'] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_salary)


Employees with Salary > 50,000:
        Name   ID Department  Salary
1      Arun  102         IT   55000
2    Vamshi  103    Finance   72000
4  Srinidhi  105  Marketing   65000


In [30]:
sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nSorted by Salary (Descending):\n", sorted_df)


Sorted by Salary (Descending):
        Name   ID Department  Salary
2    Vamshi  103    Finance   72000
4  Srinidhi  105  Marketing   65000
1      Arun  102         IT   55000
3     Sneha  104         IT   50000
0    Nandhu  101         HR   48000


In [31]:
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus:\n", df)


DataFrame with Bonus:
        Name   ID Department  Salary   Bonus
0    Nandhu  101         HR   48000  4800.0
1      Arun  102         IT   55000  5500.0
2    Vamshi  103    Finance   72000  7200.0
3     Sneha  104         IT   50000  5000.0
4  Srinidhi  105  Marketing   65000  6500.0


In [32]:
total_expense = (df['Salary'] + df['Bonus']).sum()
print("\nTotal Salary Expense (including bonuses):", total_expense)


Total Salary Expense (including bonuses): 319000.0


In [33]:
df.to_csv("employee_data.csv", index=False)
print("\nData saved to employee_data.csv")


Data saved to employee_data.csv
