<a href="https://colab.research.google.com/github/NandhithaMilkuri/Batch20_1352_PDS/blob/main/Lab3_Assisgnment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
scores = np.random.randint(50, 101, size=(4, 4))
print("Test Scores (4x4):\n", scores, "\n")


Test Scores (4x4):
 [[92 82 60 75]
 [65 50 76 55]
 [53 56 60 66]
 [58 58 92 60]] 



In [3]:
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("Row-wise Means:", row_means)
print("Column-wise Means:", col_means, "\n")

Row-wise Means: [77.25 61.5  58.75 67.  ]
Column-wise Means: [67.  61.5 72.  64. ] 



In [4]:
std_dev = np.std(scores)
variance = np.var(scores)
print("Standard Deviation (overall):", std_dev)
print("Variance (overall):", variance, "\n")

Standard Deviation (overall): 12.922243419778162
Variance (overall): 166.984375 



In [6]:
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("Global Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index, "\n")


Global Max: 92 at index (np.int64(0), np.int64(0))
Global Min: 50 at index (np.int64(1), np.int64(1)) 



In [7]:
median = np.median(scores)
print("Median (overall):", median)

Median (overall): 60.0


In [8]:
import numpy as np

image = np.random.randint(0, 256, (3, 3, 3), dtype=np.uint8)
print("Original RGB Image Array:\n", image, "\n")

Original RGB Image Array:
 [[[  2 169  17]
  [175 148 121]
  [195 133 254]]

 [[200 192 128]
  [ 19  94  43]
  [187  39  52]]

 [[198 179  27]
  [220  61 153]
  [138  49 108]]] 



In [11]:
red_channel   = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel  = image[:, :, 2]
print("Red Channel:\n", red_channel, "\n")
print("Green Channel:\n", green_channel, "\n")
print("Blue Channel:\n", blue_channel, "\n")

Red Channel:
 [[  2 175 195]
 [200  19 187]
 [198 220 138]] 

Green Channel:
 [[169 148 133]
 [192  94  39]
 [179  61  49]] 

Blue Channel:
 [[ 17 121 254]
 [128  43  52]
 [ 27 153 108]] 



In [12]:
avg_red   = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue  = np.mean(blue_channel)

print("Average Intensities - R:", avg_red,
      "G:", avg_green,
      "B:", avg_blue, "\n")


Average Intensities - R: 148.22222222222223 G: 118.22222222222223 B: 100.33333333333333 



In [13]:
bright_image = np.clip(image + 50, 0, 255)
print("Brightened Image Array:\n", bright_image, "\n")

Brightened Image Array:
 [[[ 52 219  67]
  [225 198 171]
  [245 183  48]]

 [[250 242 178]
  [ 69 144  93]
  [237  89 102]]

 [[248 229  77]
  [ 14 111 203]
  [188  99 158]]] 

