<a href="https://colab.research.google.com/github/NandhithaMilkuri/Batch20_1352_PDS/blob/main/Lab3_File_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
fp=open("example.txt","w")
fp.write("Hello,B.Tech students!\n")
fp.write("This is file handling in python.\n")
fp.write("SR University.\n")
fp.write("Suresh kumar\n")
fp.close()
print("Data Written Succesfully")

Data Written Succesfully


In [20]:
file=open("example.txt","r")
content=file.read()
print(content)
file.close()

Hello,B.Tech students!
This is file handling in python.
SR University.
Suresh kumar


In [28]:
file=open("example.txt","r")
line1=file.readline()
line2=file.readline()
print("First line : ",line1)
print("Second Line: ",line2)
file.close()

First line :  Hello,B.Tech students!

Second Line:  This is file handling in python.



In [35]:
file=open("example.txt","r")
line3=file.readline()
line4=file.readline()
print("Third line : ",line3)
print("Fourth Line: ",line4)
file.close()


Third line :  Hello,B.Tech students!

Fourth Line:  This is file handling in python.



In [31]:
file=open("example.txt","r")
lines=file.readlines()
print(lines)
file.close()

['Hello,B.Tech students!\n', 'This is file handling in python.\n', 'SR University.\n', 'Suresh kumar']


In [38]:
file=open("example.txt","a")
file.write("Appending new data...\n")
file.close()

In [39]:
with open("example.txt","r") as file:
    content=file.read()
    print(content)

Hello,B.Tech students!
This is file handling in python.
SR University.
Suresh kumar
Appending new data...



In [40]:
import csv
with open("data.csv","w",newline="") as fp:
    wr=csv.writer(fp)
    wr.writerows([["Name","Age","Course"],["aaa",21,"CSE"],["bbb",20,"ECE"]])
with open("data.csv","r") as fp:
    rd=csv.reader(fp)
    for row in rd:
        print(row)

['Name', 'Age', 'Course']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [42]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)

1D Array: [1 2 3 4]


In [43]:
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [44]:
zeros_arr=np.zeros((3,3))
print("Zeros Array:\n",zeros_arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
ones_zeros=np.ones((2,4))
print("Ones Array:\n",ones_zeros)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
range_arr=np.arange(0,10,2)
print("Range Array:\n",range_arr)

Range Array:
 [0 2 4 6 8]


In [47]:
rand_arr=np.random.rand(3,3)
print("Random Array:\n",rand_arr)

Random Array:
 [[0.95884572 0.21487193 0.83131773]
 [0.13145207 0.34222437 0.74847535]
 [0.03652966 0.35702093 0.36134231]]


In [48]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape: ",arr.shape)
print("dimensions: ",arr.ndim)
print("size: ",arr.size)
print("data type: ",arr.dtype)
print("size:",arr.size)
print("Item size",arr.itemsize)

shape:  (2, 3)
dimensions:  2
size:  6
data type:  int64
size: 6
Item size 8


In [49]:
arr=np.array([10,20,30,40,50])
print("First Element,",arr[0])
print("Last Element,",arr[-1])
print("Slice[1:4]",arr[1:4])
print("Every second element: ",arr[::2])

First Element, 10
Last Element, 50
Slice[1:4] [20 30 40]
Every second element:  [10 30 50]


In [50]:
arr2=np.array([[1,2,3],[4,5,6]])
print("Element at Row 1,Colume 2: ",arr2[0,1])
print("Second row Column: ",arr2[1,:])
print("Second Column: ",arr2[:,1])

Element at Row 1,Colume 2:  2
Second row Column:  [4 5 6]
Second Column:  [2 5]


In [52]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition: ",a+b)
print("Subtraction: ",a-b)
print("Multiplication: ",a*b)
print("Division: ",a/b)
print("Power: ",a**2)

Addition:  [5 7 9]
Subtraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]
Power:  [1 4 9]


In [60]:
arr = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Square root:", np.sqrt([1, 4, 9]))
print("Exponential:", np.exp([1, 2]))
print("Logarithm:", np.log([1, np.e,np.e**2]))


Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Square root: [1. 2. 3.]
Exponential: [2.71828183 7.3890561 ]
Logarithm: [0. 1. 2.]


In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Sum along axis 0:", np.sum(arr, axis=0))  # Column-wise sum
print("Sum along axis 1:", np.sum(arr, axis=1))

Sum: 21
Max: 6
Min: 1
Mean: 3.5
Standard Deviation: 1.707825127659933
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [62]:
a = np.array([1, 2, 3])
b = 5
print("Add scalar to array:", a + b)  # [6 7 8]

c = np.array([[1], [2], [3]])
d = np.array([4, 5, 6])
print("Broadcasted sum:\n",c+d)

Add scalar to array: [6 7 8]
Broadcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(A, B))
print("Transpose:\n", A.T)
print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004


In [65]:
import numpy as np

# Marks of students in 3 subjects
marks = np.array([
    [85, 90, 88],
    [78, 81, 85],
    [92, 89, 95]
])

print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks,axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
